services:
  cabinas-uji:
    image: ghcr.io/adriadam10/cabinas-uji:latest
    container_name: cabinas-uji
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data # Persist cache
    restart: always
    environment:
      - NODE_ENV=production
